apiVersion: apps/v1
kind: Deployment
metadata:
  name: af-admin-deployment
spec:
  selector:
    matchLabels:
      app: af-admin
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '8080'
      labels:
        app: af-admin
    spec:
      containers:
        - name: af-admin-app
          image: autofox.azurecr.io/afadmin:732
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          resources:
            requests:
              memory: '200Mi'
              cpu: '200m'
            limits:
              memory: '250Mi'
              cpu: '250m'