# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
trigger:
- main


variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '6d92ac4a-b7f1-4f33-8a26-e179f7be1014'
  imageRepository: 'afadmin'
  containerRegistry: 'autofox.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
  - stage: Prepare
    displayName: Prepare
    jobs:
      - job: Build
        pool:
          vmImage: $(vmImageName)
        displayName: Prepare
        steps:
         - script: |
            echo "CD" 
            pwd
            echo "Path" 
            echo "$(Build.Repository.LocalPath)"
           displayName: 'View'

         - task: AzureCLI@2 
           displayName: Azure CLI
           inputs:
              azureSubscription: "CDNGroupRepo"
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |
                  az config set extension.use_dynamic_install=yes_without_prompt
                  az storage blob upload-batch -d files --account-name repocdn -s "./configuration" 
                  az storage blob upload-batch -d files --account-name repocdn -s "./i18n" 
                  az cdn profile list 
                  az cdn endpoint purge  --resource-group CDNGroupRepo --name repocdn --profile-name repocdn --content-paths "/*"
                   
         
                  